[template]
ignore = [
    ".vscode/",
    "target",
    "tests/target",
    "Cargo.lock",
    "./README.md",
    "scripts/",
]

exclude = [
    "plugin_types/*/lib.rs",
    "**/plugin_types.rs"
]

[placeholders]
github-username = { prompt = "Enter the github username for the plugin_manager repo", type = "string" }
workspace = { prompt = "Is this template being generated inside an existing workspace?", type = "bool", default = false }

[hooks]
pre = ["plugin_manager.rhai"]
